#!/usr/bin/env python3
"""NeuroRift v2 — Reporter. Generates HackerOne-ready markdown security reports."""

from datetime import datetime
from pathlib import Path
from typing import List, TYPE_CHECKING

import neurocore

if TYPE_CHECKING:
    from session.state import SessionState, Finding


REPORT_TEMPLATE = """# NeuroRift Security Assessment Report

**Target:** {target}
**Date:** {date}
**Generated by:** NeuroRift v2 | DemonKing369.0

---

## Executive Summary

{executive_summary}

**Total findings:** {total_findings}

| Severity | Count |
|----------|-------|
| CRITICAL | {count_critical} |
| HIGH     | {count_high} |
| MEDIUM   | {count_medium} |
| LOW      | {count_low} |
| INFO     | {count_info} |

---

## Timeline

{timeline}

---

## Findings

{findings_section}

---

## Remediation Summary

{remediation_section}

---

*Report generated by NeuroRift v2 — github.com/Arunking9*
"""

FINDING_TEMPLATE = """### [{severity}] {title}

**Affected URL:** `{affected_url}`  
**Severity:** {severity}  

**Description:**
{description}

**Steps to Reproduce:**
{steps}

**Impact:**
{impact}

**Evidence:**
```
{evidence}
```

**Remediation:**
{remediation}

---
"""


class Reporter:
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, target: str, state: "SessionState") -> str:
        findings = state.findings
        severity_counts = {
            s: sum(1 for f in findings if f.severity == s)
            for s in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        }

        findings_md = (
            "\n".join(
                FINDING_TEMPLATE.format(
                    severity=f.severity,
                    title=f.title,
                    affected_url=f.affected_url,
                    description=f.description,
                    steps=getattr(f, "steps_to_reproduce", "See description."),
                    impact=getattr(f, "impact", "See description."),
                    evidence=f.evidence or "N/A",
                    remediation=f.remediation or "See remediation section.",
                )
                for f in sorted(
                    findings,
                    key=lambda x: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"].index(
                        x.severity
                    ),
                )
            )
            or "No findings."
        )

        remediation_md = (
            "\n".join(
                f"- **{f.title}** ({f.severity}): {f.remediation or 'No specific remediation provided.'}"
                for f in findings
            )
            or "No remediation items."
        )

        timeline = (
            "\n".join(
                f"- `{o.timestamp}` — {o.tool_name}({o.target})"
                for o in state.tool_outputs
            )
            or "No tool executions recorded."
        )

        report = REPORT_TEMPLATE.format(
            target=target,
            date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            executive_summary=f"Automated security assessment of {target} completed. "
            f"{len(findings)} finding(s) identified.",
            total_findings=len(findings),
            count_critical=severity_counts["CRITICAL"],
            count_high=severity_counts["HIGH"],
            count_medium=severity_counts["MEDIUM"],
            count_low=severity_counts["LOW"],
            count_info=severity_counts["INFO"],
            timeline=timeline,
            findings_section=findings_md,
            remediation_section=remediation_md,
        )

        messages = [
            {
                "role": "system",
                "content": "You are an expert security reporter. Polish the following report formatting.",
            },
            {"role": "user", "content": report},
        ]

        neurocore.load_model("report_writing")
        resp = neurocore.infer(messages)
        neurocore.unload_model()

        final_report = resp.get("content", report) if isinstance(resp, dict) else report

        out_path = self.output_dir / f"report_{state.session_id}.md"
        out_path.write_text(final_report, encoding="utf-8")
        return str(out_path)
